site_name: mcbootflash
site_url: https://mcbootflash.readthedocs.io/
theme: material
nav:
  - Home: index.md
  - API Reference: flash.md
  - Protocol Specification: protocol.md
  - Developer Guide: develop.md
plugins:
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_style: numpy
            members_order: source
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences