site_name: mcbootflash
site_author: Alexander Bessman
copyright: "Copyright © 2023 Alexander Bessman"
site_url: https://bessman.github.io/mcbootflash/
repo_url: https://github.com/bessman/mcbootflash/
theme: material
nav:
  - Home: index.md
  - API Reference: api.md
  - Developer's Guide: develop.md
  - Changelog: changelog.md
plugins:
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_style: numpy
            members_order: source
  - autorefs
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
