name: Build

on:
  - push

jobs:

  strategy:
    matrix:
      version: ['3.12']
      os: [ubuntu-22.04, windows-2022, macos-13]
  build-macos:

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Build
      run: tox -e build
    - name: Zip
      run: |
        zip dist/mcbootflash macos.zip 
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: uploads
        path: macos.zip  

  build-linux:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Build
      run: tox -e build
    - name: Zip
      run: |
        zip dist/mcbootflash linux.zip 
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: uploads
        path: linux.zip       

  build-windows:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Build
      run: tox -e build
    - name: Zip
      run: |
        zip dist/mcbootflash windows.zip 
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: uploads
        path: windows.zip     