name: Build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        include:
          - os: ubuntu-22.04
            name: linux
          - os: macos-13
            name: macos
          - os: windows-2022
            name: windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Build
      run: tox -e build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: dist/mcbootflash*
